### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by danez**

### CODE REVIEW

**Comment by mochja** [comment]
@danez seems like this does not play well with https://github.com/webpack/webpack-dev-server/releases/tag/v3.11.0.

I'm getting

```
Fatal error: webpack-dev-server is outdated. Please ensure you have at least version 3.2.0 installed.
```

**Comment by danez** [comment]
Thanks will check.

**Comment by danez** [comment]
This is fixed in 4.0.1

**Pull request merged**
