### PR TITLE
docs(readme): updates for JSF maintainers

### PR DESCRIPTION
**Pull request by d3viant0ne**
As part of the effort to reach compliance with JSF and get the CLA bot enabled, maintainers need to be clearly displayed.

While I was at it, I did the updates to the readme using the template chosen for the standards effort.

### CODE REVIEW

**Comment by danez** [comment]
Isn't this outside of JSF, as the CLA is also not enabled on this repo? Other than that I don't really like to have my face there and don't see the point.

**Comment by d3viant0ne** [comment]
CLA is being enabled for the entire `webpack-contrib` organization

**Comment by danez** [comment]
No it's okay. ¯\_(ツ)_/¯

**Comment by d3viant0ne** [comment]
@danez - The CLA assistant has been turned back on by the JS Foundation. If there are no other updates requested, could you land this so we can remain compliant with their requirements?

**Comment by d3viant0ne** [comment]
ty sir

**Comment by danez** [comment]
thank you :)

**Pull request merged**
